# This is a basic workflow to help you get started with Actions
# Testing 
name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [windows-2019]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
    
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
    
    - name: Install Specific NuGet Packages
      run: |
        nuget install Antlr3.Runtime -Version 3.4.1.9004 -OutputDirectory packages
        nuget install Newtonsoft.Json -Version 5.0.8 -OutputDirectory packages
        nuget install Microsoft.Web.Infrastructure -Version 1.0.0.0 -OutputDirectory packages
        nuget install Microsoft.AspNet.WebApi.Client -Version 4.0.20710.0 -OutputDirectory packages

    - name: Restore NuGet packages
      run: nuget restore BugGuardian.MVC.sln
      
    - name: Create directories
      run: |
        mkdir -p ./publish

    - name: Build the Solution
      run: msbuild BugGuardian.MVC.sln /p:Configuration=Release /p:WebPublishMethod=FileSystem

    - name: Publish Project
      run: msbuild /p:DeployOnBuild=true /p:Configuration=Release /p:Platform="Any CPU" BugGuardian.MVC/BugGuardian.MVC.csproj /p:OutputPath=./publish

    - uses: actions/upload-artifact@v3
      with:
        name: dotnet-artifact
        path: ./BugGuardian.MVC/publish/
    
