//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MA2AAPI.PushNotiWCF {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PushNotiWCF.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/PushToAndroid", ReplyAction="http://tempuri.org/IService/PushToAndroidResponse")]
        MA2AAPI.PushNotiWCF.PushToAndroidResponse PushToAndroid(MA2AAPI.PushNotiWCF.PushToAndroidRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/PushToAndroid", ReplyAction="http://tempuri.org/IService/PushToAndroidResponse")]
        System.Threading.Tasks.Task<MA2AAPI.PushNotiWCF.PushToAndroidResponse> PushToAndroidAsync(MA2AAPI.PushNotiWCF.PushToAndroidRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/PushToApple", ReplyAction="http://tempuri.org/IService/PushToAppleResponse")]
        MA2AAPI.PushNotiWCF.PushToAppleResponse PushToApple(MA2AAPI.PushNotiWCF.PushToAppleRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/PushToApple", ReplyAction="http://tempuri.org/IService/PushToAppleResponse")]
        System.Threading.Tasks.Task<MA2AAPI.PushNotiWCF.PushToAppleResponse> PushToAppleAsync(MA2AAPI.PushNotiWCF.PushToAppleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/PushToAppleOTP", ReplyAction="http://tempuri.org/IService/PushToAppleOTPResponse")]
        MA2AAPI.PushNotiWCF.PushToAppleOTPResponse PushToAppleOTP(MA2AAPI.PushNotiWCF.PushToAppleOTPRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/PushToAppleOTP", ReplyAction="http://tempuri.org/IService/PushToAppleOTPResponse")]
        System.Threading.Tasks.Task<MA2AAPI.PushNotiWCF.PushToAppleOTPResponse> PushToAppleOTPAsync(MA2AAPI.PushNotiWCF.PushToAppleOTPRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PushToAndroid", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PushToAndroidRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string message;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string title;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string notificationId;
        
        public PushToAndroidRequest() {
        }
        
        public PushToAndroidRequest(string token, string message, string title, string notificationId) {
            this.token = token;
            this.message = message;
            this.title = title;
            this.notificationId = notificationId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PushToAndroidResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PushToAndroidResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool PushToAndroidResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string error;
        
        public PushToAndroidResponse() {
        }
        
        public PushToAndroidResponse(bool PushToAndroidResult, string error) {
            this.PushToAndroidResult = PushToAndroidResult;
            this.error = error;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PushToApple", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PushToAppleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string message;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int Badgecount;
        
        public PushToAppleRequest() {
        }
        
        public PushToAppleRequest(string token, string message, int Badgecount) {
            this.token = token;
            this.message = message;
            this.Badgecount = Badgecount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PushToAppleResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PushToAppleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool PushToAppleResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string error;
        
        public PushToAppleResponse() {
        }
        
        public PushToAppleResponse(bool PushToAppleResult, string error) {
            this.PushToAppleResult = PushToAppleResult;
            this.error = error;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PushToAppleOTP", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PushToAppleOTPRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string message;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string OTP;
        
        public PushToAppleOTPRequest() {
        }
        
        public PushToAppleOTPRequest(string token, string message, string OTP) {
            this.token = token;
            this.message = message;
            this.OTP = OTP;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PushToAppleOTPResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PushToAppleOTPResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool PushToAppleOTPResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string error;
        
        public PushToAppleOTPResponse() {
        }
        
        public PushToAppleOTPResponse(bool PushToAppleOTPResult, string error) {
            this.PushToAppleOTPResult = PushToAppleOTPResult;
            this.error = error;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : MA2AAPI.PushNotiWCF.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<MA2AAPI.PushNotiWCF.IService>, MA2AAPI.PushNotiWCF.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MA2AAPI.PushNotiWCF.PushToAndroidResponse MA2AAPI.PushNotiWCF.IService.PushToAndroid(MA2AAPI.PushNotiWCF.PushToAndroidRequest request) {
            return base.Channel.PushToAndroid(request);
        }
        
        public bool PushToAndroid(string token, string message, string title, string notificationId, out string error) {
            MA2AAPI.PushNotiWCF.PushToAndroidRequest inValue = new MA2AAPI.PushNotiWCF.PushToAndroidRequest();
            inValue.token = token;
            inValue.message = message;
            inValue.title = title;
            inValue.notificationId = notificationId;
            MA2AAPI.PushNotiWCF.PushToAndroidResponse retVal = ((MA2AAPI.PushNotiWCF.IService)(this)).PushToAndroid(inValue);
            error = retVal.error;
            return retVal.PushToAndroidResult;
        }
        
        public System.Threading.Tasks.Task<MA2AAPI.PushNotiWCF.PushToAndroidResponse> PushToAndroidAsync(MA2AAPI.PushNotiWCF.PushToAndroidRequest request) {
            return base.Channel.PushToAndroidAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MA2AAPI.PushNotiWCF.PushToAppleResponse MA2AAPI.PushNotiWCF.IService.PushToApple(MA2AAPI.PushNotiWCF.PushToAppleRequest request) {
            return base.Channel.PushToApple(request);
        }
        
        public bool PushToApple(string token, string message, int Badgecount, out string error) {
            MA2AAPI.PushNotiWCF.PushToAppleRequest inValue = new MA2AAPI.PushNotiWCF.PushToAppleRequest();
            inValue.token = token;
            inValue.message = message;
            inValue.Badgecount = Badgecount;
            MA2AAPI.PushNotiWCF.PushToAppleResponse retVal = ((MA2AAPI.PushNotiWCF.IService)(this)).PushToApple(inValue);
            error = retVal.error;
            return retVal.PushToAppleResult;
        }
        
        public System.Threading.Tasks.Task<MA2AAPI.PushNotiWCF.PushToAppleResponse> PushToAppleAsync(MA2AAPI.PushNotiWCF.PushToAppleRequest request) {
            return base.Channel.PushToAppleAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MA2AAPI.PushNotiWCF.PushToAppleOTPResponse MA2AAPI.PushNotiWCF.IService.PushToAppleOTP(MA2AAPI.PushNotiWCF.PushToAppleOTPRequest request) {
            return base.Channel.PushToAppleOTP(request);
        }
        
        public bool PushToAppleOTP(string token, string message, string OTP, out string error) {
            MA2AAPI.PushNotiWCF.PushToAppleOTPRequest inValue = new MA2AAPI.PushNotiWCF.PushToAppleOTPRequest();
            inValue.token = token;
            inValue.message = message;
            inValue.OTP = OTP;
            MA2AAPI.PushNotiWCF.PushToAppleOTPResponse retVal = ((MA2AAPI.PushNotiWCF.IService)(this)).PushToAppleOTP(inValue);
            error = retVal.error;
            return retVal.PushToAppleOTPResult;
        }
        
        public System.Threading.Tasks.Task<MA2AAPI.PushNotiWCF.PushToAppleOTPResponse> PushToAppleOTPAsync(MA2AAPI.PushNotiWCF.PushToAppleOTPRequest request) {
            return base.Channel.PushToAppleOTPAsync(request);
        }
    }
}
